import type { Metadata } from "next";
import { Funnel_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "@/utils/trpc/client";

const funnelSans = Funnel_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TeraBox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html suppressHydrationWarning lang="en">
        <ClerkProvider>
          <body className={`${funnelSans.className}   dark`}>
            <main>{children}</main>
          </body>
        </ClerkProvider>
      </html>
    </TRPCReactProvider>
  );
}
