import type { Metadata } from "next";
import { Funnel_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "@/utils/trpc/client";
import { AppSidebar } from "@/components/layout/side-bar";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppHeader } from "@/components/layout/app-header";

const funnelSans = Funnel_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TeraBox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
        <ClerkProvider>
        <TRPCReactProvider>
          <body className={`${funnelSans.className}   dark`}>
            <main>{children}</main>
          </body>
        </TRPCReactProvider>
    </ClerkProvider>
      </html>
  );
}
